Replace filter
sous-chefs/line pull request #136
Opened 2019-01-21 07:14 UTC by MarkGibbons

### Description

Add the replace filter

### Issues Resolved

Adds new function.

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2019-01-21 20:08 UTC, tas50 commented on CHANGELOG.md
> +# Unreleased - for target version 2.3.0 in mid Janary 2018
```suggestion
# Unreleased - for target version 2.3.0 in mid January 2019
```

2019-01-22 07:15 UTC, MarkGibbons commented on CHANGELOG.md
> +# Unreleased - for target version 2.3.0 in mid Janary 2018
Fixed

2019-03-27 17:36 UTC, JohnRoesler requested changes
Some conflicts to clean up also

2019-03-27 17:36 UTC, JohnRoesler commented on spec/unit/library/filter/after_spec.rb
> +  it 'should insert a line that matches the pattern by default, nil implies safe' do
should not?

2019-03-27 17:36 UTC, JohnRoesler commented on spec/unit/library/filter/replace_spec.rb
> +  it 'should raise error if the pattern matchs the replacement lines' do
```suggestion
  it 'should raise error if the pattern matches the replacement lines' do
```

2019-03-27 17:36 UTC, JohnRoesler commented on spec/unit/library/filter/replace_spec.rb
> +  it 'should not raise error if the pattern matchs the replacement lines, force the change' do
```suggestion
  it 'should not raise error if the pattern matches the replacement lines, force the change' do
```

2019-03-31 04:44 UTC, kitchen-porter commented
<!--
  0 Errors
  1 Warning: This is a big Pull Request.
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-03-31 22:57 UTC, JohnRoesler approved these changes

2019-04-01 15:46 UTC, merged